//change
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext";
import { AccountProvider } from "../contexts/AccountContext";
import { OnboardingProvider } from "../contexts/OnboardingContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <AuthProvider>
          <AccountProvider>
            <OnboardingProvider>
              {children}
            </OnboardingProvider>
          </AccountProvider>
        </AuthProvider>
      </body>
    </html>
  );
}